-- =============================================================================
-- Modular In-App Gaming Ecosystem — Transactional Schema (MySQL 8.x, InnoDB)
-- =============================================================================
-- DBA notes:
--   * Points are stored as WHOLE units in BIGINT. NEVER use FLOAT/DOUBLE for
--     currency-like values. If fractional points are ever required, migrate to
--     DECIMAL(20,4) — never a binary float.
--   * `users.points_balance` is the authoritative fast-read balance and is the
--     row locked with FOR UPDATE during a bet. `points_ledger` is the immutable
--     audit trail; every mutation writes a ledger row carrying balance_after so
--     the balance can be fully reconstructed / reconciled.
--   * UNSIGNED balance + CHECK constraint + guarded UPDATE give three
--     independent layers of protection against a negative balance.
-- =============================================================================

SET NAMES utf8mb4;

-- -----------------------------------------------------------------------------
-- users — points account (the row locked during a bet)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  user_id        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_uid   CHAR(36)        NOT NULL COMMENT 'Stable id carried in the app JWT',
  points_balance BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status         ENUM('ACTIVE','SUSPENDED','CLOSED') NOT NULL DEFAULT 'ACTIVE',
  created_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
                                 ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  UNIQUE KEY uq_users_external_uid (external_uid),
  CONSTRAINT chk_users_balance_nonneg CHECK (points_balance >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- games_directory — the "plugin registry" for the factory pattern
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS games_directory (
  game_id      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  game_key     VARCHAR(64)     NOT NULL COMMENT 'Stable slug used by the game plugin',
  display_name VARCHAR(128)    NOT NULL,
  game_type    ENUM('SKILL','LUCK') NOT NULL,
  status       ENUM('ACTIVE','INACTIVE','MAINTENANCE') NOT NULL DEFAULT 'ACTIVE',
  min_bet      BIGINT UNSIGNED NOT NULL DEFAULT 1,
  max_bet      BIGINT UNSIGNED NOT NULL,
  created_at   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
                               ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (game_id),
  UNIQUE KEY uq_games_key (game_key),
  CONSTRAINT chk_games_bet_range CHECK (min_bet >= 1 AND max_bet >= min_bet)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- game_sessions — one row per initiated play. session_id is a client-facing UUIDv4
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS game_sessions (
  session_id      CHAR(36)        NOT NULL COMMENT 'UUIDv4 generated by the API',
  user_id         BIGINT UNSIGNED NOT NULL,
  game_id         BIGINT UNSIGNED NOT NULL,
  points_bet      BIGINT UNSIGNED NOT NULL,
  status          ENUM('ACTIVE','SETTLED','CANCELLED','EXPIRED') NOT NULL DEFAULT 'ACTIVE',
  payout          BIGINT UNSIGNED NULL COMMENT 'Authoritative points credited at settlement (0 = loss); NULL until settled',
  game_metadata   JSON            NULL COMMENT 'Server-side per-session game state (e.g. chamber layout, multiplier). NEVER returned to clients raw.',
  idempotency_key CHAR(64)        NULL COMMENT 'Optional client key to dedupe double-submits',
  created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  settled_at      TIMESTAMP       NULL,
  PRIMARY KEY (session_id),
  -- Idempotency is scoped PER USER: one user's key can never collide with, or
  -- resolve to, another user's session (prevents cross-account replay / IDOR).
  UNIQUE KEY uq_sessions_user_idem (user_id, idempotency_key),
  KEY idx_sessions_user (user_id, created_at),
  KEY idx_sessions_game (game_id),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (user_id),
  CONSTRAINT fk_sessions_game FOREIGN KEY (game_id) REFERENCES games_directory (game_id),
  CONSTRAINT chk_sessions_bet_pos CHECK (points_bet >= 1),
  -- Defense in depth mirroring MAX_PAYOUT in gameSettlementService.js: a DB-layer
  -- ceiling so no code path can persist an absurd payout. Keep the two in sync.
  CONSTRAINT chk_sessions_payout_cap CHECK (payout IS NULL OR payout <= 1000000000000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- points_ledger — append-only double-entry-style audit trail (source of truth)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS points_ledger (
  ledger_id     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id       BIGINT UNSIGNED NOT NULL,
  session_id    CHAR(36)        NULL,
  entry_type    ENUM('DEBIT','CREDIT') NOT NULL,
  reason        ENUM('GAME_BET','GAME_PAYOUT','COUPON_REDEEM','REFERRAL_BONUS','ADJUSTMENT','SKILL_REWARD')
                                NOT NULL,
  amount        BIGINT          NOT NULL COMMENT 'Signed: negative for DEBIT, positive for CREDIT',
  balance_after BIGINT UNSIGNED NOT NULL COMMENT 'Running balance snapshot for reconciliation',
  reference     VARCHAR(64)     NULL COMMENT 'External ref (e.g. skill_session_id) when session_id FK does not apply',
  created_at    TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (ledger_id),
  KEY idx_ledger_user (user_id, created_at),
  KEY idx_ledger_session (session_id),
  CONSTRAINT fk_ledger_user FOREIGN KEY (user_id) REFERENCES users (user_id),
  CONSTRAINT fk_ledger_session FOREIGN KEY (session_id) REFERENCES game_sessions (session_id),
  CONSTRAINT chk_ledger_sign CHECK (
    (entry_type = 'DEBIT'  AND amount < 0) OR
    (entry_type = 'CREDIT' AND amount > 0)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Enforce append-only at the DB layer (defense in depth).
DROP TRIGGER IF EXISTS trg_points_ledger_no_update;
DROP TRIGGER IF EXISTS trg_points_ledger_no_delete;
DELIMITER //
CREATE TRIGGER trg_points_ledger_no_update BEFORE UPDATE ON points_ledger
FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'points_ledger is append-only'//
CREATE TRIGGER trg_points_ledger_no_delete BEFORE DELETE ON points_ledger
FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'points_ledger is append-only'//
DELIMITER ;

-- -----------------------------------------------------------------------------
-- leaderboard_scores — durable source of truth for leaderboards. Redis Sorted
-- Sets are the hot cache in front of this table; if Redis is offline or cold,
-- reads fall back to this table, and it is used to rehydrate Redis.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leaderboard_scores (
  period_type ENUM('global','daily','weekly') NOT NULL,
  period_key  VARCHAR(32)     NOT NULL COMMENT "'global' | 'YYYY-MM-DD' (day) | week-start 'YYYY-MM-DD'",
  user_id     BIGINT UNSIGNED NOT NULL,
  score       BIGINT          NOT NULL DEFAULT 0,
  updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (period_type, period_key, user_id),
  -- Serves the top-N fallback query without a filesort.
  KEY idx_leaderboard_rank (period_type, period_key, score DESC, user_id),
  CONSTRAINT fk_leaderboard_user FOREIGN KEY (user_id) REFERENCES users (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- skill_sessions — lifecycle for Part B skill/engagement games. The client
-- plays locally after /api/skill/start; /api/skill/submit validates the claimed
-- result server-side and awards a SKILL_REWARD. status guards single-submit.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS skill_sessions (
  session_id   CHAR(36)        NOT NULL,
  user_id      BIGINT UNSIGNED NOT NULL,
  game_id      BIGINT UNSIGNED NOT NULL,
  status       ENUM('STARTED','SUBMITTED','EXPIRED') NOT NULL DEFAULT 'STARTED',
  issued_at    BIGINT UNSIGNED NOT NULL COMMENT 'epoch ms the seed token was issued (for submit deadline + time plausibility)',
  score        BIGINT          NULL,
  reward       BIGINT UNSIGNED NULL,
  created_at   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMP       NULL,
  PRIMARY KEY (session_id),
  KEY idx_skill_user (user_id, created_at),
  CONSTRAINT fk_skill_user FOREIGN KEY (user_id) REFERENCES users (user_id),
  CONSTRAINT fk_skill_game FOREIGN KEY (game_id) REFERENCES games_directory (game_id),
  -- Defense in depth mirroring config.skill.maxReward (keep in sync): a DB-layer
  -- ceiling so no code path can persist an absurd skill reward.
  CONSTRAINT chk_skill_reward_cap CHECK (reward IS NULL OR reward <= 100000),
  CONSTRAINT chk_skill_score_nonneg CHECK (score IS NULL OR score >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- skill_high_scores — per-game best score (keep-max), the durable store behind
-- the skill high-score leaderboard (Redis ZADD GT is the hot cache).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS skill_high_scores (
  game_id    BIGINT UNSIGNED NOT NULL,
  user_id    BIGINT UNSIGNED NOT NULL,
  best_score BIGINT          NOT NULL,
  updated_at TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (game_id, user_id),
  KEY idx_skill_hs_rank (game_id, best_score DESC, user_id),
  CONSTRAINT fk_skillhs_user FOREIGN KEY (user_id) REFERENCES users (user_id),
  CONSTRAINT fk_skillhs_game FOREIGN KEY (game_id) REFERENCES games_directory (game_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------------------------------
-- coupons — defined for completeness (not touched by /api/game/initiate)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS coupons (
  coupon_id       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code            VARCHAR(32)     NOT NULL,
  points_value    BIGINT UNSIGNED NOT NULL,
  max_redemptions INT UNSIGNED    NOT NULL DEFAULT 1,
  redeemed_count  INT UNSIGNED    NOT NULL DEFAULT 0,
  status          ENUM('ACTIVE','DISABLED','EXPIRED') NOT NULL DEFAULT 'ACTIVE',
  valid_from      TIMESTAMP       NULL,
  valid_until     TIMESTAMP       NULL,
  created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (coupon_id),
  UNIQUE KEY uq_coupon_code (code),
  CONSTRAINT chk_coupon_redemptions CHECK (redeemed_count <= max_redemptions)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
